INSERT INTO TRANSACTION_CATEGORY(ID, NAME) VALUES (1, 'pensja');
INSERT INTO TRANSACTION_CATEGORY(ID, NAME) VALUES (2, 'zakupy');

INSERT INTO ACCOUNTING_PERIOD(ID, START_DATE, DURATION) VALUES (1, '2020-01-01', 31);
INSERT INTO ACCOUNTING_PERIOD(ID, START_DATE, DURATION) VALUES (2, '2020-02-01', 29);

INSERT INTO TRANSACTION(ID, DATE_OFFSET, DESCRIPTION, VALUE, TRANSACTION_CATEGORY_ID, ACCOUNTING_PERIOD_ID) VALUES (1, 10, 'zakupy 1', -200, 2, 1);
INSERT INTO TRANSACTION(ID, DATE_OFFSET, DESCRIPTION, VALUE, TRANSACTION_CATEGORY_ID, ACCOUNTING_PERIOD_ID) VALUES (2, 0, 'premia', 1000, 1, 1);
INSERT INTO TRANSACTION(ID, DATE_OFFSET, DESCRIPTION, VALUE, TRANSACTION_CATEGORY_ID, ACCOUNTING_PERIOD_ID) VALUES (3, 15, 'zakupy 2', -500, 2, 1);

INSERT INTO TRANSACTION(ID, DATE_OFFSET, DESCRIPTION, VALUE, TRANSACTION_CATEGORY_ID, ACCOUNTING_PERIOD_ID) VALUES (4, 0, 'wypłata', 500, 1, 2);
