INSERT INTO CATEGORY (ID, NAME) VALUES (1, 'dochody');
INSERT INTO CATEGORY (ID, NAME) VALUES (2, 'wydatki');

INSERT INTO SUBCATEGORY (ID, NAME, CATEGORY_ID) VALUES (1, 'pensja', 1);
INSERT INTO SUBCATEGORY (ID, NAME, CATEGORY_ID) VALUES (2, '500+', 1);
INSERT INTO SUBCATEGORY (ID, NAME, CATEGORY_ID) VALUES (3, 'zakupy', 2);
INSERT INTO SUBCATEGORY (ID, NAME, CATEGORY_ID) VALUES (4, 'niewiadomoco', 2);

INSERT INTO MONTH (ID, YEAR, MONTH) VALUES (1, 2020, 1);
INSERT INTO MONTH (ID, YEAR, MONTH) VALUES (2, 2020, 2);

INSERT INTO PREDICTION (ID, VALUE, MONTH_ID, CATEGORY_ID) VALUES (1, 10500, 1, 1);
INSERT INTO PREDICTION (ID, VALUE, MONTH_ID, CATEGORY_ID) VALUES (2, -7000, 1, 2);

INSERT INTO TRANSACTION (ID, DAY, DESCRIPTION, VALUE, MONTH_ID, SUBCATEGORY_ID) VALUES (1, 1, 'wypłata', 10000, 1, 1);
INSERT INTO TRANSACTION (ID, DAY, DESCRIPTION, VALUE, MONTH_ID, SUBCATEGORY_ID) VALUES (2, 1, 'premia', 1000, 1, 1);
INSERT INTO TRANSACTION (ID, DAY, DESCRIPTION, VALUE, MONTH_ID, SUBCATEGORY_ID) VALUES (3, 10, NULL, 500, 1, 2);
INSERT INTO TRANSACTION (ID, DAY, DESCRIPTION, VALUE, MONTH_ID, SUBCATEGORY_ID) VALUES (4, 15, 'Lidl', -300, 1, 3);
INSERT INTO TRANSACTION (ID, DAY, DESCRIPTION, VALUE, MONTH_ID, SUBCATEGORY_ID) VALUES (5, 21, 'Rossmann', -200, 1, 3);
INSERT INTO TRANSACTION (ID, DAY, DESCRIPTION, VALUE, MONTH_ID, SUBCATEGORY_ID) VALUES (6, 28, 'IKEA', -2500, 1, 3);
