CREATE TABLE CATEGORY (
    ID BIGINT AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE (NAME)
);

CREATE TABLE MONTH (
    ID BIGINT AUTO_INCREMENT,
    MONTH INTEGER NOT NULL,
    YEAR INTEGER NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE (YEAR, MONTH)
);

CREATE TABLE PREDICTION (
    ID BIGINT AUTO_INCREMENT,
    VALUE BIGINT NOT NULL,
    CATEGORY_ID BIGINT,
    MONTH_ID BIGINT,
    PRIMARY KEY (ID),
    UNIQUE (MONTH_ID, CATEGORY_ID),
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(ID),
    FOREIGN KEY (MONTH_ID) REFERENCES MONTH(ID)
);

CREATE TABLE SUBCATEGORY (
    ID BIGINT AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    CATEGORY_ID BIGINT,
    PRIMARY KEY (ID),
    UNIQUE (NAME, CATEGORY_ID),
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(ID)
);

CREATE TABLE TRANSACTION (
    ID BIGINT AUTO_INCREMENT,
    DAY INTEGER NOT NULL,
    DESCRIPTION VARCHAR(255),
    VALUE BIGINT  NOT NULL,
    MONTH_ID BIGINT,
    SUBCATEGORY_ID BIGINT,
    PRIMARY KEY (ID),
    FOREIGN KEY (MONTH_ID) REFERENCES MONTH(ID),
    FOREIGN KEY (SUBCATEGORY_ID) REFERENCES SUBCATEGORY(ID)
);
