create table category (
                          id bigint generated by default as identity,
                          name varchar(255) not null,
                          primary key (id)
);

create table month (
                       id bigint generated by default as identity,
                       month integer not null,
                       year integer not null,
                       primary key (id)
);

create table prediction (
                            id bigint generated by default as identity,
                            value bigint not null,
                            category_id bigint,
                            month_id bigint,
                            primary key (id)
);

create table subcategory (
                             id bigint generated by default as identity,
                             name varchar(255) not null,
                             category_id bigint,
                             primary key (id)
);

create table transaction (
                             id bigint generated by default as identity,
                             day integer not null,
                             description varchar(255),
                             value bigint not null,
                             month_id bigint,
                             subcategory_id bigint,
                             primary key (id)
);

alter table category
    add constraint unique_category_name unique (name);

alter table month
    add constraint unique_year_month unique (year, month);

alter table prediction
    add constraint unique_prediction unique (month_id, category_id);

alter table subcategory
    add constraint uniqie_subcategory unique (name, category_id);

alter table prediction
    add constraint fk_prediction_category
        foreign key (category_id)
            references category;

alter table prediction
    add constraint fk_prediction_month
        foreign key (month_id)
            references month;

alter table subcategory
    add constraint fk_subcategory_category
        foreign key (category_id)
            references category;

alter table transaction
    add constraint fk_transaction_month
        foreign key (month_id)
            references month;

alter table transaction
    add constraint fk_transaction_subcategory
        foreign key (subcategory_id)
            references subcategory;
